# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ControleTreinamento(object):
    def setupUi(self, ControleTreinamento):
        ControleTreinamento.setObjectName("ControleTreinamento")
        ControleTreinamento.resize(422, 203)
        self.gridLayout_2 = QtWidgets.QGridLayout(ControleTreinamento)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupbox = QtWidgets.QGroupBox(ControleTreinamento)
        self.groupbox.setObjectName("groupbox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupbox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupbox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.btn_cliqueAqui = QtWidgets.QPushButton(self.groupbox)
        self.btn_cliqueAqui.setObjectName("btn_cliqueAqui")
        self.gridLayout.addWidget(self.btn_cliqueAqui, 2, 0, 1, 1)
        self.ln_pop = QtWidgets.QLineEdit(self.groupbox)
        self.ln_pop.setObjectName("ln_pop")
        self.gridLayout.addWidget(self.ln_pop, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupbox, 0, 0, 1, 1)

        self.retranslateUi(ControleTreinamento)
        QtCore.QMetaObject.connectSlotsByName(ControleTreinamento)

    def retranslateUi(self, ControleTreinamento):
        _translate = QtCore.QCoreApplication.translate
        ControleTreinamento.setWindowTitle(_translate("ControleTreinamento", "Relatorio de Controle de Treinamento"))
        self.label.setText(_translate("ControleTreinamento", "Escreva abaixo qual POP deseja pegar o levantamento para treinamento?"))
        self.btn_cliqueAqui.setText(_translate("ControleTreinamento", "Clique aqui"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ControleTreinamento = QtWidgets.QDialog()
    ui = Ui_ControleTreinamento()
    ui.setupUi(ControleTreinamento)
    ControleTreinamento.show()
    sys.exit(app.exec_())
